# Generated by Django 4.1 on 2024-01-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=0, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.CharField(choices=[('wifi', 'Wi-Fi'), ('parking', 'Parking'), ('kitchen', 'Kitchen'), ('ac', 'Air Conditioning'), ('pet', 'Animal')], max_length=20),
        ),
    ]
