# Generated by Django 4.1 on 2024-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_alter_ownerprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
