# Generated by Django 4.1 on 2024-01-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_ownerprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
