# Generated by Django 4.1 on 2024-01-22 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('no_of_room', models.IntegerField()),
                ('no_of_bathroom', models.IntegerField()),
                ('no_of_hall', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_photo', models.ImageField(blank=True, null=True, upload_to='room_photos/')),
                ('hall_photo', models.ImageField(blank=True, null=True, upload_to='room_photos/')),
                ('kitchen_photo', models.ImageField(blank=True, null=True, upload_to='room_photos/')),
                ('bathroom_photo', models.ImageField(blank=True, null=True, upload_to='room_photos/')),
                ('parking_area_photo', models.ImageField(blank=True, null=True, upload_to='room_photos/')),
                ('amenities', models.ManyToManyField(to='userauth.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
