# Generated by Django 4.1 on 2024-01-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_amenity_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
