# Generated by Django 4.1 on 2024-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_room_latitude_room_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
