# Generated by Django 4.1 on 2024-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_ownerprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
