# Generated by Django 4.1 on 2024-01-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_ownerprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
