# Generated by Django 4.1 on 2024-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_alter_ownerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_photos/'),
        ),
    ]
