# Generated by Django 4.1 on 2024-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_tenantprofile_address_tenantprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
